export const languages: any = {
  en: { name: "English", nativeName: "English" },
  af: { name: "Afrikaans", nativeName: "Afrikaans" },
  ak: { name: "Akan", nativeName: "Akan" },
  sq: { name: "Albanian", nativeName: "Shqip" },
  am: { name: "Amharic", nativeName: "አማርኛ" },
  ar: { name: "Arabic", nativeName: "العربية" },
  hy: { name: "Armenian", nativeName: "Հայերեն" },
  as: { name: "Assamese", nativeName: "অসমীয়া" },
  ay: { name: "Aymara", nativeName: "aymar aru" },
  az: { name: "Azerbaijani", nativeName: "azərbaycan dili" },
  bm: { name: "Bambara", nativeName: "bamanankan" },
  eu: { name: "Basque", nativeName: "euskara, euskera" },
  be: { name: "Belarusian", nativeName: "Беларуская" },
  bn: { name: "Bengali", nativeName: "বাংলা" },
  bh: { name: "Bihari", nativeName: "भोजपुरी" },
  bs: { name: "Bosnian", nativeName: "bosanski jezik" },
  bg: { name: "Bulgarian", nativeName: "български език" },
  my: { name: "Burmese", nativeName: "ဗမာစာ" },
  ca: { name: "Catalan; Valencian", nativeName: "Català" },
  ny: { name: "Chichewa; Chewa; Nyanja", nativeName: "chiCheŵa, chinyanja" },
  zh: { name: "Chinese", nativeName: "中文 (Zhōngwén), 汉语, 漢語" },
  co: { name: "Corsican", nativeName: "corsu, lingua corsa" },
  hr: { name: "Croatian", nativeName: "hrvatski" },
  cs: { name: "Czech", nativeName: "česky, čeština" },
  da: { name: "Danish", nativeName: "dansk" },
  dv: { name: "Divehi; Dhivehi; Maldivian;", nativeName: "ދިވެހި" },
  eo: { name: "Esperanto", nativeName: "Esperanto" },
  et: { name: "Estonian", nativeName: "eesti, eesti keel" },
  ee: { name: "Ewe", nativeName: "Eʋegbe" },
  fi: { name: "Finnish", nativeName: "suomi, suomen kieli" },
  fr: { name: "French", nativeName: "français, langue française" },
  gl: { name: "Galician", nativeName: "Galego" },
  ka: { name: "Georgian", nativeName: "ქართული" },
  de: { name: "Deutsch", nativeName: "Deutsch" },
  el: { name: "Greek, Modern", nativeName: "Ελληνικά" },
  gn: { name: "Guaraní", nativeName: "Avañeẽ" },
  gu: { name: "Gujarati", nativeName: "ગુજરાતી" },
  ht: { name: "Haitian; Haitian Creole", nativeName: "Kreyòl ayisyen" },
  ha: { name: "Hausa", nativeName: "Hausa, هَوُسَ" },
  he: { name: "Hebrew (modern)", nativeName: "עברית" },
  hi: { name: "Hindi", nativeName: "हिन्दी, हिंदी" },
  id: { name: "Indonesian", nativeName: "Bahasa Indonesia" },
  ga: { name: "Irish", nativeName: "Gaeilge" },
  ig: { name: "Igbo", nativeName: "Asụsụ Igbo" },
  is: { name: "Icelandic", nativeName: "Íslenska" },
  it: { name: "Italian", nativeName: "Italiano" },
  ja: { name: "Japanese", nativeName: "日本語 (にほんご／にっぽんご)" },
  jv: { name: "Javanese", nativeName: "basa Jawa" },
  kn: { name: "Kannada", nativeName: "ಕನ್ನಡ" },
  kk: { name: "Kazakh", nativeName: "Қазақ тілі" },
  km: { name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  rw: { name: "Kinyarwanda", nativeName: "Ikinyarwanda" },
  ky: { name: "Kirghiz, Kyrgyz", nativeName: "кыргыз тили" },
  ko: { name: "Korean", nativeName: "한국어 (韓國語), 조선말 (朝鮮語)" },
  la: { name: "Latin", nativeName: "latine, lingua latina" },
  lb: { name: "Luxembourgish, Letzeburgesch", nativeName: "Lëtzebuergesch" },
  lg: { name: "Luganda", nativeName: "Luganda" },
  ln: { name: "Lingala", nativeName: "Lingála" },
  lo: { name: "Lao", nativeName: "ພາສາລາວ" },
  lt: { name: "Lithuanian", nativeName: "lietuvių kalba" },
  lv: { name: "Latvian", nativeName: "latviešu valoda" },
  mk: { name: "Macedonian", nativeName: "македонски јазик" },
  mg: { name: "Malagasy", nativeName: "Malagasy fiteny" },
  ms: { name: "Malay", nativeName: "bahasa Melayu, بهاس ملايو‎" },
  ml: { name: "Malayalam", nativeName: "മലയാളം" },
  mt: { name: "Maltese", nativeName: "Malti" },
  mi: { name: "Māori", nativeName: "te reo Māori" },
  mr: { name: "Marathi (Marāṭhī)", nativeName: "मराठी" },
  mn: { name: "Mongolian", nativeName: "монгол" },
  nb: { name: "Norwegian Bokmål", nativeName: "Norsk bokmål" },
  ne: { name: "Nepali", nativeName: "नेपाली" },
  no: { name: "Norwegian", nativeName: "Norsk" },
  om: { name: "Oromo", nativeName: "Afaan Oromoo" },
  or: { name: "Oriya", nativeName: "ଓଡ଼ିଆ" },
  pa: { name: "Panjabi, Punjabi", nativeName: "ਪੰਜਾਬੀ, پنجابی‎" },
  pi: { name: "Pāli", nativeName: "पाऴि" },
  fa: { name: "Persian", nativeName: "فارسی" },
  pl: { name: "Polish", nativeName: "polski" },
  ps: { name: "Pashto, Pushto", nativeName: "پښتو" },
  pt: { name: "Portuguese", nativeName: "Português" },
  qu: { name: "Quechua", nativeName: "Runa Simi, Kichwa" },
  ro: { name: "Romanian, Moldavian, Moldovan", nativeName: "română" },
  ru: { name: "Russian", nativeName: "русский язык" },
  sa: { name: "Sanskrit (Saṁskṛta)", nativeName: "संस्कृतम्" },
  sd: { name: "Sindhi", nativeName: "सिन्धी, سنڌي، سندھی‎" },
  sm: { name: "Samoan", nativeName: "gagana faa Samoa" },
  sr: { name: "Serbian", nativeName: "српски језик" },
  gd: { name: "Scottish Gaelic; Gaelic", nativeName: "Gàidhlig" },
  sn: { name: "Shona", nativeName: "chiShona" },
  si: { name: "Sinhala, Sinhalese", nativeName: "සිංහල" },
  sk: { name: "Slovak", nativeName: "slovenčina" },
  sl: { name: "Slovene", nativeName: "slovenščina" },
  so: { name: "Somali", nativeName: "Soomaaliga, af Soomaali" },
  st: { name: "Southern Sotho", nativeName: "Sesotho" },
  es: { name: "Spanish", nativeName: "español, castellano" },
  su: { name: "Sundanese", nativeName: "Basa Sunda" },
  sw: { name: "Swahili", nativeName: "Kiswahili" },
  sv: { name: "Swedish", nativeName: "svenska" },
  ta: { name: "Tamil", nativeName: "தமிழ்" },
  te: { name: "Telugu", nativeName: "తెలుగు" },
  tg: { name: "Tajik", nativeName: "тоҷикӣ, toğikī, تاجیکی‎" },
  th: { name: "Thai", nativeName: "ไทย" },
  ti: { name: "Tigrinya", nativeName: "ትግርኛ" },
  tk: { name: "Turkmen", nativeName: "Türkmen, Түркмен" },
  tl: { name: "Tagalog", nativeName: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔" },
  tr: { name: "Turkish", nativeName: "Türkçe" },
  ts: { name: "Tsonga", nativeName: "Xitsonga" },
  tt: { name: "Tatar", nativeName: "татарча, tatarça, تاتارچا‎" },
  ug: { name: "Uighur, Uyghur", nativeName: "Uyƣurqə, ئۇيغۇرچە‎" },
  uk: { name: "Ukrainian", nativeName: "українська" },
  ur: { name: "Urdu", nativeName: "اردو" },
  uz: { name: "Uzbek", nativeName: "zbek, Ўзбек, أۇزبېك‎" },
  vi: { name: "Vietnamese", nativeName: "Tiếng Việt" },
  cy: { name: "Welsh", nativeName: "Cymraeg" },
  fy: { name: "Western Frisian", nativeName: "Frysk" },
  xh: { name: "Xhosa", nativeName: "isiXhosa" },
  yi: { name: "Yiddish", nativeName: "ייִדיש" },
  yo: { name: "Yoruba", nativeName: "Yorùbá" },
};

export const languageArray = Object.keys(languages).map((key) => ({
  label: languages[key].name,
  value: key,
  nativeName: languages[key].nativeName,
}));
